exclude: ^(externals|build)/

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format (via uv)
        entry: uv tool run ruff format
        language: system
        types: [python]
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|cc|cpp|cxx|h|hpp)$
